### ISSUE TITLE
No multiline IRC

### ISSUE THREAD

**Issue by Petraea** [nooitaf/nurdbar#5]
The IRC client doesn't handle multiple line messages both receiving and sending.

**Comment by nooitaf** [comment]
https://github.com/nooitaf/nurdbar/issues/1

**Comment by sanderfoobar** [comment]
ah dat
is jammer

**Comment by nooitaf** [comment]
well it does, but its not shown on the bar-screen

**Comment by nooitaf** [comment]
multi line messages are now properly word-wrapped and should work on any screen size
